name: gnn
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - boost=1.74.0
  - boost-cpp=1.74.0
  - bzip2=1.0.8
  - ca-certificates=2021.5.30
  - cairo=1.16.0
  - certifi=2021.5.30
  - cycler=0.10.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - glib=2.68.2
  - icu=67.1
  - joblib=1.0.1
  - jpeg=9d
  - kiwisolver=1.3.1
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - ncurses=6.2
  - numpy=1.19.4
  - olefile=0.46
  - openssl=1.1.1k
  - pandas=1.1.4
  - patsy=0.5.1
  - pcre=8.44
  - pillow=8.0.1
  - pip=21.1.1
  - pixman=0.38.0
  - pthread-stubs=0.4
  - pycairo=1.20.0
  - pyparsing=2.4.7
  - python=3.8.10
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2021.1
  - rdkit=2020.09.2
  - readline=8.1
  - reportlab=3.5.55
  - scikit-learn=0.23.2
  - scipy=1.5.3
  - setuptools=52.0.0
  - sqlalchemy=1.3.20
  - sqlite=3.35.4
  - statsmodels=0.12.1
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.1
  - wheel=0.36.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - chardet==3.0.4
    - colorama==0.4.3
    - ignnition==1.0.2
    - jmespath==0.10.0
    - keras==2.4.3
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - oauthlib==3.1.0
    - requests==2.23.0
    - rsa==4.0
    - six==1.14.0
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - tensorboardx==1.9
    - tensorflow==2.3.0
    - tensorflow-estimator==2.3.0
prefix: /home/rmonge/miniconda3/envs/gnn
